version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: project-qwerty-app
    restart: on-failure
    working_dir: /var/www/app
    volumes:
      - ../app:/var/www/app

  nginx:
    image: nginx:1.19-alpine
    container_name: project-qwerty-nginx
    restart: on-failure
    ports:
      - 8000:80
    volumes:
      - ../app:/var/www/app
      - ./nginx:/etc/nginx/conf.d
