version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: project-qwerty-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../app:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: project-qwerty-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../app:/var/www
      - ./nginx:/etc/nginx/conf.d
