version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: qwerty-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../app:/var/www/

  nginx:
    image: nginx:1.19-alpine
    container_name: qwerty-nginx
    restart: always
    ports:
      - 8005:80
    volumes:
      - ../app:/var/www/
      - ./nginx:/etc/nginx/conf.d

  db:
    image: postgres:14-alpine
    container_name: qwerty-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres
    volumes:
      - db-postgres-data:/var/lib/postgresql/data:rw

volumes:
  db-postgres-data:
